# Site settings
title: Scrollol
email: me@iamacoder.com
description: > # Simple page scroller written in vanilla JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
markdown: redcarpet
